### ISSUE TITLE
client.character.create_new_conversation stopped returning the promise

### ISSUE THREAD

**Issue by wang-yuwen** [KevinAdhaikal/CAINode#10]
For some reason it just stopped returning its promise. The function does work, _but_ I'm using it with an await and it fails to return the promise. It all started just yesterday. Any ideas why? 
I used to get unresolved promises before, with other requests but not every time, more like 1 in 100 requests, randomly. 
I think it's something to do with c.ai itself but can't seem to find what causes it. Can you look into it?

**Comment by KevinAdhaikal** [comment]
can you give me a result of the log, please? or some example

**Comment by wang-yuwen** [comment]
I'm using it with a telegram bot that has an in-built timeout module (p-timeout), so it waits for the promise to resolve and throws an error if it is still pending after a set amound of time. So the error i'm getting is 
`TimeoutError: Promise timed out after 20000 milliseconds`

The function i'm using first awaits for `await client.character.create_new_conversation()` and then should do some other stuff but it doesn't get past the first line, so the promise i'm awaiting for is stuck pending, and that causes the other stuff to timeout as well. 

As i've mentioned, this used to happen randomly with other c.ai requests as well, but now it happens every time with this particular function. 

Also it should be noted that the function _does work_, I just can't await for it.

**Comment by KevinAdhaikal** [comment]
hmmmm... maybe it's my `send_ws` fault?
i will try to investigate later.

**Comment by KevinAdhaikal** [comment]
btw, are you set with_greeting parameter to `true`? i mean, you called `create_new_conversation` function like this
`client.character.create_new_conversation(true)` or `client.character.create_new_conversation()`

**Comment by matsukky** [comment]
i don't know for the op, but for myself, `create_new_conversation(true)`, `create_new_conversation()` and `create_new_conversation(false)` result to the same things... Block in an infinite wait.

**Comment by KevinAdhaikal** [comment]
> i don't know for the op, but for myself, `create_new_conversation(true)`, `create_new_conversation()` and `create_new_conversation(false)` result to the same things... Block in an infinite wait.

ohhhh...

**Comment by KevinAdhaikal** [comment]
I just found out that it's my `send_ws` issue, not the server's. I will fix it ASAP.

**Comment by KevinAdhaikal** [comment]
i am an idiot 😂 

i just fix the `send_ws` i will update to the NPM later.

**Comment by KevinAdhaikal** [comment]
okay done. i've just update to the NPM as well.
now you can try it now. @wang-yuwen @matsukky

**Comment by wang-yuwen** [comment]
Okay, I'm a little bit late but as for your question, yes, It was set to true. Not that it matters now that you've fixed it.
Thank you, I'll try it out now. Strange, though, that it used to work just fine until one day.

**Comment by wang-yuwen** [comment]
Hmm...

```
TypeError: Cannot read properties of undefined (reading 'chat_id')
at Character_Class.create_new_conversation (.../index.js:1383:81)
```

**Comment by KevinAdhaikal** [comment]
> Hmm...
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'chat_id')
> at Character_Class.create_new_conversation (.../index.js:1383:81)
> ```

If you set greeting to true, then it has 2 array
[0] is contains chat id
[1] is for greeting

If you set greeting to false, it not returns array.

Maybe you can try console.log()

**Comment by matsukky** [comment]
`create_new_conversation(false)` seems to work as it should.... But as has say wang-yuwen, `create_new_conversation(true )` or `create_new_conversation()` return :

```
TypeError: Cannot read properties of undefined (reading 'chat_id')
at Character_Class.create_new_conversation (.../index.js:1383:81)
```
console.log() change nothing.

**Comment by KevinAdhaikal** [comment]
Hmmmmmm... Did you connect to character? @matsukky and @wang-yuwen

**Comment by KevinAdhaikal** [comment]
oh, I'm such an idiot 😂 
i forgot to put `result` variable with array zero. i mean, like this: `if (this.#prop.join_type == 1) this.#prop.current_chat_id = result[0].chat.chat_id` at [index.js line 1383](https://github.com/KevinAdhaikal/CAINode/blob/fdbec51eb971b18a416a73c0e07871646b8cdb0b/index.js#L1383)

thanks for letting me out.

**Comment by KevinAdhaikal** [comment]
I will update the NPM Package later because I'm adding some character.ai API now.

**Comment by KevinAdhaikal** [comment]
For now, you can clone, get the `index.js` file, and put it into your project.

**Comment by KevinAdhaikal** [comment]
Hey guys! I've just updated it to V1.2.0!
If you get any issue with `client.character.create_new_conversation`, please re open the issue.

Thanks.
